# Site settings
# 网站标题
title: 唐万锂的博客 
header-img: "img/green.jpg"
tagline: "cn"  
# 网站描述，这个主要用于seo，告诉搜索引擎一个关于您站点的简单描述，通常建议在其中包含您网站的关键词
description: "唐万锂|读而立·写而生"  
author: "唐万锂"
baseurl: ""
# 自己网站的网址
url: "http://tangwanli.com"  
# 网站的根目录
root:

# About/contact
# owner里面如果加东西的话会在下面的name里面报错
owner: 
  name: " 唐万锂"
  email: 771147315@qq.com
  bio: "分享知识也是一种快乐"

# Data
gavatar: http://dreamofbook.qiniudn.com/Az..png
favicon: img/favicon.png

douban_username:  
twitter_username: 
github_username: 
facebook_username: rockTang
weibo_username: 
zhihu_username: 

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 8
# exclude: 转换时候排除某些文件夹或文件。被排除的文件或文件夹的路径是相对于网站源码目录的，源码目录以外不受影响。
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
# 网站时区
timezone: Asia/Shanghai

# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "唐万锂"
      header-img: "img/green.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 
comments :
  provider : duoshuo
  duoshuo :
    short_name : 
  disqus :
      short_name : 

# Analytics and webmaster tools stuff goes here
google_analytics: 
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation