permalink: /:title   #博文的固定链接
paginate: 10                                #分页时每页博文数量
author: 唐万锂                             #自定义常亮
  name: 唐万锂
  email: 771147315@qq.com
  link: http://yansu.org
title: 唐万锂的博客                             #自定义常量
locals:                                     #自定义常量
  tags: 标签
  about: 关于
active: 技术                                 #自定义常量
subscribe_rss: /pages/atom.xml              #订阅地址
markdown: redcarpet                         #markdown解释器