# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings，主要用于网站头部header
title: 唐万锂的博客
brief-intro: It's my life. # 这个是一个小的描述
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tangwanli.com" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links，主要用于网站底部footer
twitter_username: 
facebook_username: tangwanli
github_username:  tangwanli
email: 771147315@qq.com
weibo_username: 
zhihu_username: 771147315
linkedIn_username: 
dribbble_username:

description_footer: 本站记录我前端之旅的沿途风景！

# comments
# two ways to comment, only choose one, and use your own short name
# 两种评论插件，选一个就好了，使用自己的 short_name
duoshuo_shortname: #hygblog
disqus_shortname: gaohaoyang

# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxx字符串
baidu_tongji_id: cf8506e0ef223e57ff6239944e5d46a4
google_analytics_id: UA-72449510-4 # google 分析追踪id

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt。文章中存在的4次换行为摘要分割符，换行前的内容会以摘要的形式显示在主页Home上，进入文章页不影响。
excerpt_separator: "\n\n\n\n"

# paginate
gems: [jekyll-paginate]
paginate: 6
